### ISSUE TITLE
db_download error: 0it [00:00, ?it/s]

### ISSUE THREAD

**Issue by EWisely** [gjeunen/reference_database_creator#11]
Hi!  I love the functionality to download a list of taxa from NCBI!  I'm trying it now, and for most species in my list, it works as expected.   For some species in the same list, I get the "No such file or directory: 'esearch_output.txt'" error mentioned earlier (which I will try to narrow down and see if that fixes it) and for other species in my list, I get the following error:

downloading sequences from NCBI
looking up the number of sequences that match the query
found 394 number of sequences matching the query
starting the download
formatting the downloaded sequencing file to CRABS format
0it [00:00, ?it/s]
found 0 sequences with incorrect accession format
written 0 sequences to Stenella frontalis_ncbi.fasta

what could be the problem here?

Thanks for a great tool!
~Eldridge

**Comment by EWisely** [comment]
I think I fixed that error by changing the --keep_original flag to yes.

**Comment by hughcross** [comment]
Thanks for the input, Eldridge. And thanks for cross-posting on the other issue. We will have a look at the code and see where the issue is.

**Comment by EWisely** [comment]
with the --keep_originals flag set to yes, it no longer throws the errors... however, it does append the fasta records for the previous species to the beginning of the file for the current species, such that the file for the final species in the list contains the fasta records for the whole list.  
I hope this helps with the debugging!  
I'm going to rename the last one from the list to reflect that it's from the whole list and delete the rest of the files.  It's not as elegant as the original way is designed, but it appears to get the job done!

**Comment by gjeunen** [comment]
Hello @EWisely,

Thanks for posting the error message. The first "No such file or directory: 'esearch_output.txt'" is pointing towards a failure to connect to the NCBI servers. Similarly, the second error message is also pointing towards a failure to connect to the NCBI servers, but at a different point in the process. It might have been that there was unusual high traffic on their servers, making it unstable. The `--keep_originals` parameter should not have an impact on the server connection, as it is just an IF statement to remove a file. Glad you managed to download the files though and please let me know if you keep encountering this issue.

For the second part, could you please provide a bit more info on what is going on? I might be misunderstanding something, but it seems that you're running the `db_download` function multiple times (using different output filenames?), but CRABS still appends the sequences to the first output file? Could you please share the code you used and I'll look into this in the coming days.

Best,
Gert-Jan
