### ISSUE TITLE
cutadapt has an option called --revcomp

### ISSUE THREAD

**Issue by billzt** [gjeunen/reference_database_creator#13]
Hi all, from the source code I see that cutadapt has been called twice to run, among which another once is on reverse-complemented sequences.

However cutadapt has already had the --revcomp option: https://cutadapt.readthedocs.io/en/stable/guide.html#reverse-complement

How about using this option to make cutadapt run only once?

**Comment by gjeunen** [comment]
Hello @billzt,

Thank you very much for the comment. I'll have a look at the --revcomp option and update the code if the same results can be achieved compared to the current implementation.

Thanks again!

Cheers,
Gert-Jan

**Comment by gjeunen** [comment]
Hello @billzt,

Thank you very much for the comment. I'll have a look at the --revcomp option and update the code if the same results can be achieved compared to the current implementation.

Thanks again!

Cheers,
Gert-Jan
