### ISSUE TITLE
Restarting embl download using existing files after OOM

### ISSUE THREAD

**Issue by laninsky** [gjeunen/reference_database_creator#16]
Kia ora GJ, Hugh et al.,

@bigdog-836 and I have successfully downloaded all the \*.dat files through embl for VRT\* using the following code:
```
crabs db_download --source embl --database 'VRT*' --output embl_vrt.fasta --keep_original yes
```

However, it seems we suffered an OOM going from the *.dat files:
<img width="657" alt="image" src="https://user-images.githubusercontent.com/8808649/215370245-571e104e-b55a-4598-bc90-d7ffdc46a671.png">
to the downstream *.fasta files.

Is there a way to "restart" the "download" to utilise the existing *.dat files? And, what is a realistic memory amount to request for the 'fasta conversion' step  (we requested 1GB). Should this actually be equal to the size of the largest *.dat file (i.e. is it trying to read the whole file into memory)?

Thanks for the help guys - you know how much I struggle with python :)

**Comment by gjeunen** [comment]
Hello @laninsky and @bigdog-836,

Currently there is no option in CRABS to restart from the point at which the error occurred. Apologies for this! I'll be thoroughly revising CRABS in the coming months to add in these safe points and additional flexibility for when people run into these issues. 

For now, we can extract the piece of code you need and run it outside of CRABS. If you would need help with this, please let me know and I'll make this available.

Best,
Gert-Jan

**Comment by laninsky** [comment]
Ah cool, thanks GJ - option to restart would be awesome. In the meantime, it would be awesome to have the code to run the later steps from the download if it is easy enough for you to pull out for us. Any thoughts on the memory requirements? (i.e. is it reading the whole file into memory)?

**Comment by laninsky** [comment]
Kia ora GJ - I managed to muddle through with my rudimentary python abilities. I tweaked the crabs executable to `import glob` in the import modules section, and then modified the `dl_files` line under the embl download to `dl_files = glob.glob('*.dat')`. I retried the `crabs db_download --source embl --database 'VRT*' --output embl_vrt.fasta --keep_original yes` . It still died with an OOM with 10GB of RAM (but was close to finishing - 97%), so currently retrying with 50GB.

**Comment by laninsky** [comment]
Kia ora GJ - just confirming the converting to fasta for embl VRT completed successfully with 50GB. Looks like peak memory usage was just under 10GB of RAM, which is probably why it died last time.

**Comment by gjeunen** [comment]
Hello @laninsky,

Thanks for confirming you solved the issue. CRABS does indeed read the whole file in memory. I'll keep you posted on when the additional functionality is incorporated in the new version of CRABS. For now, I'll close this issue.

Thanks,
Gert-Jan
