### ISSUE TITLE
db_download not working for EMBL

### ISSUE THREAD

**Issue by mikeallen-eco** [gjeunen/reference_database_creator#23]
Hello,
The db_download function is not working for the EMBL database, presumably because they changed the URL. The output is pasted below for the mammal download script in the README:

>crabs db_download --source embl --database 'mam*' --output embl_mam.fasta --keep_original yes

Thanks,
Mike

downloading sequences from EMBL
--2023-05-21 09:29:10--  ftp://ftp.ebi.ac.uk/pub/databases/ena/sequence/con-std_latest/std/STD_mam*dat.gz
           => ‘.listing’
Resolving ftp.ebi.ac.uk (ftp.ebi.ac.uk)... 193.62.193.138
Connecting to ftp.ebi.ac.uk (ftp.ebi.ac.uk)|193.62.193.138|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/databases/ena/sequence/con-std_latest/std ... done.
==> PASV ... done.    ==> LIST ... done.

    [    <=>                                                                                         ] 68,057      25.8KB/s   in 2.6s   

2023-05-21 09:29:14 (25.8 KB/s) - ‘.listing’ saved [68057]

Removed ‘.listing’.
No matches on pattern ‘STD_mam*dat.gz’.
Combining all EMBL downloaded fasta files...
formatting intermediary file to CRABS format
0it [00:00, ?it/s]
found 0 sequences with incorrect accession format
written 0 sequences to embl_mam.fasta

**Comment by gjeunen** [comment]
Hello @mikeallen-eco,

Could you please try capitalising your entry, i.e., ‘—database MAM*’? I believe this will solve your issue. Please let me know if this doesn’t work and I’ll look into it further.

I’ll try to get the code modified, so that it will capitalise the users entry automatically.

Best regards,
Gert-Jan

**Comment by mikeallen-eco** [comment]
That worked. Thank you!

Mike

**Comment by ThomasLuypaert** [comment]
Hi @gjeunen, 

Is it possible that this work-around for downloading sequences from the EMBL database no longer works?

I have tried the following two commands:

`singularity exec /PATH_TO_CONTAINER/crabs_0.1.7.sif crabs db_download --source embl --database 'VRT*' --output embl_vrt.fasta --keep_original yes
`

and 

`singularity exec /PATH_TO_CONTAINER/crabs_0.1.7.sif crabs db_download --source embl --database 'vrt*' --output embl_vrt.fasta --keep_original yes
`

However, although the job finishes running, both result in an empty '.fasta' file. My associated error file contains a single line stating:

`
0it [00:00, ?it/s]
`

Could something be wrong with the link used to query the files?

Thanks for any input!

Cheers, 
Thomas
