### ISSUE TITLE
Unable to pull current version using docker

### ISSUE THREAD

**Issue by KristenFern** [gjeunen/reference_database_creator#24]
Hello,

I'm not able to pull the current version of crabs using docker, I get this error message:

```
docker pull quay.io/swordfish/crabs:0.1.4
Error response from daemon: unauthorized: access to the requested resource is not authorized
```
But pulling the previous version (quay.io/hughcross/crabs:0.1.3.1) works fine.

Thanks!

**Comment by gjeunen** [comment]
@hughcross, could you please check the docker error? We'll try to get this fixed asap @KristenFern, thank you very much for the notification.

Best,
Gert-Jan

**Comment by hughcross** [comment]
Hello Kristen, thank you for bringing this to our attention. I reset the permissions on the site, so it should work now. Please let us know if it is still not pulling.

**Comment by KristenFern** [comment]
Thanks Hugh and Gert-Jan, working fine now.
