### ISSUE TITLE
--method diversity 

### ISSUE THREAD

**Issue by LiLu-1** [gjeunen/reference_database_creator#25]
Hi!
I have a problem with displaying diversity.
Once I have the curated database, I run the following code

crabs visualization --method diversity --input merged_12S_insilico_pga_tax_derep_clean.tsv --level class

and I always see the two horizontal bar graph of the number of species and sequences of the same length. Comparing the MiFish-E/U chart shown in the article and mine, I think the length I see is about the number of sequences, so the number of species bar is wrong (also because in the cleaned tsv there are species repeated several times, so it is right that they are less than the number of sequences).
Could you help me? Thanks

![image](https://github.com/gjeunen/reference_database_creator/assets/135152889/9e898cdc-6e45-4671-b4d8-744456b68082)
![image](https://github.com/gjeunen/reference_database_creator/assets/135152889/25b7b971-7bc6-4321-ba77-81d6d9dd02d6)

**Comment by gjeunen** [comment]
Hello @LiLu-1,

Thank you for your query and apologies for the delayed response!

Could you please let me know which version of CRABS you're working on `crabs --version` and which installation platform (GitHub, conda, Docker)?

Best,
Gert-Jan

**Comment by LiLu-1** [comment]
Hello @gjeunen,
the CRABS version is 0.1.1 and was installed with conda. Could you assure me that the files I generated are correct until the tsv cleaned? Should I try to use docker for visualization?
Thanks for your help!

**Comment by gjeunen** [comment]
Hello @LiLu-1,

The current version of CRABS is 0.1.4. We're having issues with updating the code through conda. Could you please update your files from GitHub or Docker? Let me know if the issue of the visualization persists after updating.

Thanks,
Gert-Jan

**Comment by gjeunen** [comment]
Hello @LiLu-1,

Perfect, thanks! Yes, your reference database will be correct with the conda version. There might've been a bug in the earlier version to display the graph. My apologies!

Best,
Gert-Jan
