### ISSUE TITLE
Duplicated lines in .tsv file after assigning taxonomy step

### ISSUE THREAD

**Issue by Twrodgers** [gjeunen/reference_database_creator#28]
Hello,
the .tsv file created after step 5. assign_tax has some strange duplicated lines for some entries. 
The file looks like this (below) where everything is repeated twice for each accession number/entry. This only occurs for the first 79 entries in my case, and then the remaining entries are normal. Any idea what could be causing this? 

MW929360	254705	Eukaryota	Chordata	Mammalia	Rodentia	Sciuridae	Hylopetes	Hylopetes_alboniger	GTAAAATATAACCTCCGAATGATGCTAGCCCAGACTAGACCAGTCTAAGCTTCTATTCATTAATTGACCCAAACTTATTGATCAACGGAACA	254705	Eukaryota	Chordata	Mammalia	Rodentia	Sciuridae	Hylopetes	Hylopetes_alboniger	GTAAAATATAACCTCCGAATGATGCTAGCCCAGACTAGACCAGTCTAAGCTTCTATTCATTAATTGACCCAAACTTATTGATCAACGGAACA
MW929359	2883638	Eukaryota	Chordata	Mammalia	Rodentia	Sciuridae	Priapomys	Priapomys_leonardi	GTAAAAAACAGCCTCCGAATGATTTTTAGTCCAGACTTAACTAGTCTAAACTTCCATTCATTAATTGATCCAAACTTATTGACCAACGGAACA	2883638	Eukaryota	Chordata	Mammalia	Rodentia	Sciuridae	Priapomys	Priapomys_leonardi	GTAAAAAACAGCCTCCGAATGATTTTTAGTCCAGACTTAACTAGTCTAAACTTCCATTCATTAATTGATCCAAACTTATTGACCAACGGAACA
MW929358	2883638	Eukaryota	Chordata	Mammalia	Rodentia	Sciuridae	Priapomys	Priapomys_leonardi	GTAAAAAACAGCCTCCGAATGATTTTAGTCCAGACTTAACTAGTCTAAACTTCCATTCATTAATTGATCCAAACTTATTGACCAACGGAACA	2883638	Eukaryota	Chordata	Mammalia	Rodentia	Sciuridae	Priapomys	Priapomys_leonardi	GTAAAAAACAGCCTCCGAATGATTTTAGTCCAGACTTAACTAGTCTAAACTTCCATTCATTAATTGATCCAAACTTATTGACCAACGGAACA

**Comment by gjeunen** [comment]
Hello @Twrodgers,

Could you please let me know the version of CRABS you're working on `crabs --version` and which installation platform you used, i.e., GitHub, Docker, conda?

Best,
Gert-Jan

**Comment by Twrodgers** [comment]
Hi ,
I am using it installed from GitHub directly to a university cluster. It looks like they installed version 0.1.1, so maybe that is the problem. I will see if they can install 0.1.2 and maybe that will fix the issue?
Thanks,
Torrey

**Comment by gjeunen** [comment]
Hello @Twrodgers,

The current version Is 0.1.4. Could you please try installing this version and see if the problem persists?

Best,
Gert-Jan

**Comment by Twrodgers** [comment]
Thank you,
On the GitHub page, it is saying that the latest version is 0.1.2?
Maybe I am missing something, is there somewhere else I can find version 0.1.4?

**Comment by gjeunen** [comment]
Hello @Twrodgers,

Apologies, the latest version is 0.1.5 not 0.1.4 as stated before, as I updated the code for additional BOLD functionality a couple of days ago. On the GitHub page, you can click on the `setup.py` or `function/__init__.py` files to see the latest version. I'm assuming the version 0.1.2 you're referring to is the tar release? We'll try to update this shortly. 

@hughcross, could you please update the tar release of CRABS to the latest 0.1.5 version?

@Twrodgers, if the problem persists after installing this latest version, please let me know and I'll look into this further. Apologies for the confusion around version numbers.

Best,
Gert-Jan

**Comment by Twrodgers** [comment]
ok, I will try to get the latest version going. 
I am really excited about this software, thanks for you hard work on this!

Torrey
