### ISSUE TITLE
Issues installing with conda

### ISSUE THREAD

**Issue by A33miller** [gjeunen/reference_database_creator#32]
Kia ora,

I am having trouble downloading CRABS using conda. I get this issue:
# Crabs: Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/osx-64::__osx==10.16=0
  - crabs -> matplotlib-base -> __osx[version='>=10.11|>=10.12']

I would appreciate any advice to solve this issue.
Thank you!
Allison

**Comment by gjeunen** [comment]
@A33miller,

Thank you for your query! @hughcross, could you please check the conda installation. I think it needs to be updated.

Best,
Gert-Jan

**Comment by hughcross** [comment]
Hi @A33miller , as crabs is undergoing a lot of development, it is hard to keep the bioconda installation up to date. It takes time to get each update through, but we are working on it. In the meanwhile, I have made crabs into a Python package, which can update faster. The commands below will create a conda environment with the dependencies, then you can `pip install` to get crabs. I tried a few example commands and everything seems to be working, but I haven't checked everything. Go ahead and check it out and post back here with issues. Once we get it tested we will change the instructions on the README. 

Here are instructions for Mac (Intel chip), and should probably work with Linux and Windows with WSL. 

```
# download the yaml file with a list of dependencies:
wget https://github.com/hughcross/reference_database_creator_pypi/raw/main/crabs_0.2.0_dependencies.yml
# create the environment using the yaml file:
conda env create -n crabs_0.2.0 --file crabs_0.2.0_dependencies.yml
# activate the conda environment
conda activate crabs_0.2.0
# use pip to install crabs within this environment
pip install crabs 
```

For a mac with a newer M1 or M2 chip:

```
wget https://github.com/hughcross/reference_database_creator_pypi/raw/main/crabs_0.2.0_dependencies.yml

CONDA_SUBDIR=osx-64 conda env create -n crabs_0.2.0 --file crabs_0.2.0_dependencies.yml

conda activate crabs_0.2.0

conda config --env --set subdir osx-64

pip install crabs
```


That should give you a workable conda version of crabs with only a few more commands.
