### ISSUE TITLE
number of errors allowed in primer-binding site

### ISSUE THREAD

**Issue by slambrechts** [gjeunen/reference_database_creator#36]
Hi,

I notice the default for number of errors allowed in primer-binding site, specified with the `--error` flag when running `crabs insilico_pcr`, is set to `4.5`. I'm not sure what this means. Probably not that 4 and a half mismatches are allowed per primer-binding site, because how do you define a half mismatch? Or does this mean 4 mismatches are allowed in the fwd primer, and 5 in the reverse, or something else?

**Comment by gjeunen** [comment]
Hello @slambrechts,

The `crabs insilico_pcr --error 4.5` allows for a maximum of 4 errors in the forward and 4 errors in the reverse primer binding region. If you would like to allow for a different maximum number of errors, please always add 0.5 to the value. For example, to allow for a maximum of 3 errors instead, you can use `crabs insilico_pcr 3.5`. This is an artefact of the cutadapt submodule and the python coding language, which is implemented by CRABS. The code currently does not allow for different error numbers to be found within the forward and reverse primer binding regions. For more information on this topic, please consult the cutadapt documentation, which is very extensive and extremely helpful. The documentation can be found here: https://cutadapt.readthedocs.io/en/stable/

Best regards,
Gert-Jan

**Comment by slambrechts** [comment]
Hi @gjeunen ,

Ok, thanks for the clear explanation

Best,
Sam
