### ISSUE TITLE
Needed to merge the output of crabs insilico_pcr and crabs pga?

### ISSUE THREAD

**Issue by slambrechts** [gjeunen/reference_database_creator#37]
Hi,

If I understand correctly, it is advisable to both run `crabs insilico_pcr`, followed by `crabs pga`, but do we need to merge the output, and use that as input for `crabs assign_tax`?

Best,
Sam

**Comment by gjeunen** [comment]
Hello @slambrechts,

It is not essential to run the `crabs pga` function to build your reference database. The `crabs insilico_pcr` function will try to locate the primer-binding regions in all sequences you provide to CRABS. If your input file are all full-length sequences that cover the full region of the amplicon and the primer-binding region, all amplicons will be retrieved during the `insilico_pcr` step. For example, if the input file only contains full mitogenome sequences and you're trying to retrieve the COI amplicon from those sequences.

In some cases, the input file will contain a subset of sequences where the primer-binding region(s) might be missing. This can happen when the barcoding was done with one or both of the primers you are using in the `insilico_pcr` step or if sequences are incomplete (containing lots of `N` in a particular region). In this situation, crabs will not be able to retrieve the amplicon during the `insilico_pcr` step. Hence, running the `crabs pga` function is needed if your intent is to retrieve the amplicons from those sequences as well and want to incorporate those amplicons in your reference database.

The `crabs pga` function uses the output file from the `insilico_pcr` function as input file and the input file from the `insilico_pcr` function as a database (initially downloaded sequence file). CRABS will automatically subset the data from the raw sequence file (database) to remove the sequences for which the amplicon was already retrieved (input). CRABS will then run a pairwise global alignment against all sequences with the input file as seed sequences in the aim to retrieve amplicons for which the primer-binding regions are missing. The output file from the `crabs pga` function will contain the sequences retrieved during the `insilico_pcr` step, as well as the newly retrieved amplicons during the `pga` step. There is no need to merge the output of `crabs insilico_pcr` and `crabs pga`.

Best regards,
Gert-Jan

**Comment by slambrechts** [comment]
Hi @gjeunen,

Ok sounds perfect, thank you

Best,
Sam
