### ISSUE TITLE
crabs pga percid parameter

### ISSUE THREAD

**Issue by slambrechts** [gjeunen/reference_database_creator#38]
Hi,

Does it make sense to run `crabs pga` with a `percid` lower then 0.95? I'm trying to create databases for several invertebrate phyla for eDNA metabarcoding, one database per phylum, and each database is based on a merge of ncbi and EMBL. Do I need to set `percid` to the sequence similarity cutoff for sequences to be considered representatives of the specific phylum? Because that is often quite low, as low as 60% for example... Or is it recommended to run `crabs pga` with `percid `set at around 0.95, regardless of what taxonomic level you are building a database for?

Kind regards,
Sam

**Comment by gjeunen** [comment]
Dear @slambrechts,

Yes, you can definitely lower the percent identity threshold if you're expecting greater variance in the amplicon region. Alternatively, you could run the `pga` command multiple times with the output from the previous file as the input of the new iteration. 

Best,
Gert-Jan

**Comment by slambrechts** [comment]
Dear Gert-Jan,

Ok, thanks for the info, that second option is indeed interesting, especially because we have a time-limit on our hpc clusters.

Best,
Sam
