### ISSUE TITLE
The default value of --minlen and --maxlen in seq_cleanup is not very appropriate

### ISSUE THREAD

**Issue by billzt** [gjeunen/reference_database_creator#40]
All my sequences were gone after `seq_cleanup`. Finally I found that the reason was the "default" value of  --minlen (100) and --maxlen (500)

Many popular barcodes are less than 100bp, such as those within 12S rRNA. While there are also many COI barcodes longer than 500bp. It's difficult to define an appropriate default value to suit different research areas.

I suggest not applying the length filter  unless users define --minlen or --maxlen intentionally.

**Comment by gjeunen** [comment]
@billzt,

In the latest version of CRABS (`crabs --version 1.0.0`), the default values for `--minimum-length` and `--maximum-length` have been removed. Thank you very much for this suggestion and helping us improve CRABS for all users.

Best wishes,
Gert-Jan
