### ISSUE TITLE
db_download error

### ISSUE THREAD

**Issue by fang9319** [gjeunen/reference_database_creator#42]
System: MacOS Ventura, Python version:3.9.1 crabs:0.1.4

Code:
crabs db_download --source ncbi --database nucleotide --query '12S[All Fields] AND ("1"[SLEN] : "50000"[SLEN])' --species zhuangjiang_fish.csv --output zhujiang_fish_ncbi.fasta --keep_original yes --email myemail --batchsize 500000

error report:
Traceback (most recent call last):
  File "/Users/liuzifang/reference_database_creator/crabs", line 1428, in <module>
    main()
  File "/Users/liuzifang/reference_database_creator/crabs", line 1425, in main
    args.func(args)
  File "/Users/liuzifang/reference_database_creator/crabs", line 80, in db_download
    speciesTempFileList = wget_ncbi_species(QUERY, DATABASE, EMAIL, BATCHSIZE, OUTPUT, speciesName)
  File "/Users/liuzifang/reference_database_creator/function/module_db_download.py", line 111, in wget_ncbi_species
    print(f'downloading {seqcount} sequences from NCBI using the searchterm: {speciesSearchTerm}')
UnboundLocalError: local variable 'seqcount' referenced before assignment

I changed the script in module_db_download.py by adding seqcount=0 at line 102, also tried seqcount='', and both worked.  **When I used the newest version of Crabs on an Ubuntu desktop, I didn't encounter the same error.** So I guess it's possibly just happened in the older version of crabs, but I just think it could be helpful for people who encounter similar problems using the old versions.

**Comment by FabioGAmaral** [comment]
It's happening the same to me, crabs version: 0.1.8

**Comment by fang9319** [comment]
Hi Fabio,

It happened to me after I updated the crabs to v0.1.8 too. Try add
seqcount=0 at line 102, it will fix the problem roughly.

Best regards,
Zifang

**Comment by saraswaminathan** [comment]
I'm getting this same error but unsure how to fix when using Docker bc unsure how to edit the module_db_download.py script

**Comment by gjeunen** [comment]
Hello @saraswaminathan,

Thank you for your message. 

We're introducing a new version of CRABS tomorrow, which represents a full overhaul of the code, with added functionality, increased speed, improved file and error handling, enhanced flexibility, and simplified installation through fewer dependencies. This version will first be available by cloning the GitHub repository, with the other installation options following shortly after. The new version should also fix the error you are currently encountering. 

Best wishes,
Gert-Jan
