### ISSUE TITLE
PGA with embl database

### ISSUE THREAD

**Issue by slambrechts** [gjeunen/reference_database_creator#49]
Hi,

I'm running `crabs pga` on the embl invertebrate (inv*) database, but it is taking a long time. Is there a way in CRABS to filter the EMBL database first for a specific taxonomic group, before running in silico pcr and PGA?

```
crabs pga --input embl_inv.fasta --output Coll01_embl_inv_db_PGA.fasta --database Coll01_embl_inv_db.fasta --fwd ACGCTGTTATCCCTWAGG  --rev GACGATAAGACCCTWTAGA --speed medium --percid 0.95 --coverage 0.95 --filter_method strict

```

**Comment by gjeunen** [comment]
Hello @slambrechts,

To subset the data in CRABS, you would need to assign a taxonomy to each sequence using the `assign_tax` command, followed by the `db_subset` command. To run the in silico and pga analyses, you will need to use `db_import` function again to create the correct format.

I hope this helps.

Best,
Gert-Jan

**Comment by slambrechts** [comment]
ok great, thanks

db_subset does not seem to work, but I guess this might be because I am working with the conda version of crabs, which might be outdated?
