### ISSUE TITLE
is CRABS multithreaded? 

### ISSUE THREAD

**Issue by slambrechts** [gjeunen/reference_database_creator#50]
Hi,

Does CRABS use multiple cores? I haven't seen anything in the help messages regarding specifying the number of cores for a job, but maybe crabs uses multiple cores by default?

**Comment by gjeunen** [comment]
Hello @slambrechts,

Multi-core is only supported at specific steps, such as the in silico and PGA analyses. Core number is automatically detected and set to the max. Currently, there is no user-defined input for setting the number of cores.

Best,
Gert-Jan

**Comment by slambrechts** [comment]
ok, good to know the in silico pcr and pga are multi-core, thank you for the info!
