### ISSUE TITLE
decrease in sequences for BOLD database after assign_tax

### ISSUE THREAD

**Issue by rturba** [gjeunen/reference_database_creator#53]
Hello Gert-Jan,

There seems to be some issue when I try to run `assign_tax` for the BOLD database. When I do it with my NCBI one, there is a small decrease in reads, but nothing major. However, when I do it with the BOLD database that I've downloaded with CRABS, the drop in numbers is really high.

![image](https://github.com/gjeunen/reference_database_creator/assets/65319403/6e70562a-697c-4930-a614-0401405c3fa2)
![image](https://github.com/gjeunen/reference_database_creator/assets/65319403/bc390443-f190-4f1d-9919-295a97b10b71)

I've checked the log files after the `in_silico` and `pga` steps, and although I get a `Fatal error: Illegal character '-' in sequence on line 100 of FASTA file`, it seems to finish the run and write the sequences. In both, I get 3166 sequences. But then, I run the `assign_tax` step and it drops to 12. When I check the fasta files, I've noticed that the headers of the sequences are not necessarily accession numbers. For example, my first line has `>GBMA2505-09|Bos`, which is searchable on BOLD but not on NCBI. Is that an issue with the BOLD database per se? Or is there something I'm missing when downloading the db from the beginning?

Thanks,
Rachel

**Comment by gjeunen** [comment]
Hello @rturba,

If the sequences do not contain a valid accession number, they will be removed by CRABS during the `assign_tax` step, as CRABS uses the accession number or the CRABS unique identifier to retrieve the information on the taxonomic lineage. Would it be possible to reformat the sequences you lost to the CRABS unique identifier, so that the taxonomic lineage will be created and sequences won't be discarded?

Thanks,
Gert-Jan

**Comment by rturba** [comment]
Hello again!

So, I'm not sure how to approach this. My missing file has 531938 sequences 😬. I don't think it will be manageable to do it manually. What I find interesting is that the missing file header has, for example:

```
BSHMT018-09|Philantomba TATAGTAATACCTATCATAATTGGAGGATTCGGCAACTGACTRGTTCCCCTAATAATTGGTGCCCCAGACATGGCATTTCCTCGAATAAATAATATAAGTTTCTGACTTCTCCCTCCCTCTTTTCTATTACTCCTAGCATCCTCAATAGTTGAAGCCGGAGCAGGA
```

When I look up the BIN number on BOLD online, I can see that the sequence is identified to the spp level and also has an NCBI accession ID. I don't understand why that info didn't come with the download, though 🤔

**Comment by gjeunen** [comment]
Hello @rturba,

Can you please paste the output of the following command in your response: `head -n 50 filename`. Change `filename` to your file name. Can you also please let me know the size of the file? If the file has a set structure, I can write a small script that will reformat the document, so that you can use the `db_import` function in CRABS.

Best,
Gert-Jan

**Comment by rturba** [comment]
For sure, but I don't understand. Are you able to get the accession ID from the BIN numbers alone?

Here is the file with the 50 entries. The file in total has ~102 Mb.

[head_CO1V-U_tax_missing.txt](https://github.com/gjeunen/reference_database_creator/files/14377184/head_CO1V-U_tax_missing.txt)

**Comment by gjeunen** [comment]
Hello @rturba,

Please place the code below in a file named `processBOLD.py` in the same folder as your file for which you ran the `head` command. It is best to do this using Sublime Text or Visual Studio Code to ensure no formatting errors are occurring. Apologies for not providing the file, but .py files are apparently not attachable on GitHub.

```
#!/usr/bin/env Python3

newfile = []
with open('head_CO1V-U_tax_missing.txt', 'r') as infile:
    for line in infile:
        seq = line.split('\t')[1]
        seqHeader = '>' + line.split('\t')[0].split('|')[1] + '\n'
        newfile.append(seqHeader)
        newfile.append(seq)

with open('head_CO1V-U_tax_missing_format.fasta', 'w') as outfile:
    for item in newfile:
        outfile.write(item)
```

Open the file in a text editor and change the filename in line 4 to your file name. Currently, it is written as `head_CO1V-U_tax_missing.txt`. In the Terminal, move to the directory. You might need to make the code executable, for which you can use the following command: `chmod +x processBOLD.py`. You can then execute the program using `./processBOLD.py`. This will create the output file `head_CO1V-U_tax_missing_format.fasta`. In turn, this file can be imported into CRABS using the following command: `crabs db_import -i head_CO1V-U_tax_missing_format.fasta -o head_CO1V-U_tax_missing_format_import.fasta -d '}' -s species`. From then, you should be able to follow the CRABS help pages and your normal pipeline. 

One issue that might arise is that the sequences you provided do not have species information. In case they are still dropping out, please let me know and I'll find a work-around.

Best regards,
Gert-Jan

**Comment by rturba** [comment]
Hmmm... I'm getting an `IndexError: list index out of range`. But I understand what you're trying to do here. You're reformarting the TSV file in a FASTA format including the BIN number as the header, am I right? It's weird that the file only has the genus, but when I look up the BIN on the BOLD website, I can see the species and NCBI accession ID. So, I'm not sure what is happening. Am I the only one that is seeing this dramatic decrease in taxonomy assignment with the BOLD db? Or is that an issue with the db itself and its format?

**Comment by rturba** [comment]
This was the one that was giving me the error: https://github.com/gjeunen/reference_database_creator/issues/41

The code I used is the same one in that issue:
```
crabs-v8 db_download --source bold --database 'Chordata' --output CO1_bold.fasta --keep_original yes --marker 'COI-5P'
```

Afterwards, I also downloaded other invert sequences and merged both:
```
crabs db_download --source bold --database 'Arthropoda|Annelida|Mollusca' --output CO1_invert.fasta --keep_original no --marker 'COI-5P'

downloaded 5080 sequences from BOLD
formatting 5080 sequences to CRABS format
 94%|#########################3 | 3454922/3684972 [00:00<00:00, 17606177.37it/s]
found 75 sequences with incorrect accession format
written 4653 sequences to CO1_invert.fasta

crabs db_merge --output CRABS_CO1_bold.fasta --uniq yes --input CRABS_CO1_chor_bold_download.fasta CRABS_CO1_invert_bold_download.fasta

merging all fasta files and discarding duplicate sequence headers
found 632419 sequences in CRABS_CO1_chor_bold_download.fasta
found 4653 sequences in CRABS_CO1_invert_bold_download.fasta
written 570461 sequences to CRABS_CO1_bold.fasta
```

I'm not sure I understand what you mean with the code amendment?

Thanks!

**Comment by gjeunen** [comment]
When I run your first command,

```
crabs-v8 db_download --source bold --database 'Chordata' --output CO1_bold.fasta --keep_original yes --marker 'COI-5P'
```

The sequences without accession numbers are correctly processed using a unique CRABS ID and species name, which will be parsed properly during the `assign_tax` function. Please see output of those sequences below. In the following steps, you are using your file specified by `--output` correct? Which in the code above would be `CO1_bold.fasta`. You should not be using the extra file, which is generated from the `--keep_original` parameter. In the example, this was `CRABS_bold_download.fasta` on my system.

```
>CRABS_1:Cubiceps_pauciradiatus
CCTATATCTAGTATTTGGTGCATGAGCCGGAATAGTAGGAACGGCCTTAAGCCTGCTCATCCGAGCTGAACTAAATCAACCAGGCGCCCTACTTGGGGACGACCAGATCTACAATGTAATTGTTACGGCACACGCCTTCGTAATAATTTTCTTTATAGTAATGCCAATTATGATTGGAGGGTTTGGAAACTGGCTCATCCCCCTAATGATTGGAGCCCCAGACATGGCATTCCCCCGAATGAATAATATGAGCTTCTGACTGCTTCCTCCCTCTTTCCTGCTGCTTCTGGCTTCTTCCGGAGTTGAAGCTGGTGCCGGAACCGGTTGAACAGTCTATCCTCCCCTAGCCGGTAACCTGGCCCACGCCGGGGCATCCGTTGACCTGACTATCTTCTCCCTTCACTTAGCAGGTGTATCATCAATTCTTGGAGCAATTAACTTCATTACAACCATCATTAATATGAAACCTGCAGCTATTTCCCAATACCAAACACCCCTGTTTGTATGAGCGGTTCTAATTACAGCCGTTCTTCTCCTTCTATCTCTGCCCGTTCTTGCTGCAGGGATTACAATACTACTTACAGACCGAAATCTAAACACAACCTTCTTTGACCCTGCGGGAGGAGGGGACCCCATCCTTTATCAGCACCTG
>CRABS_2:Cubiceps_pauciradiatus
CCTATATCTAGTATTTGGTGCATGAGCCGGAATAGTAGGAACGGCCTTAAGCCTGCTCATCCGAGCTGAACTAAATCAACCAGGCGCCCTACTTGGGGACGACCAGATCTACAATGTAATTGTTACGGCACACGCCTTCGTAATAATTTTCTTTATAGTAATGCCAATTATGATTGGAGGGTTTGGAAACTGGCTCATCCCCCTAATGATTGGAGCCCCAGACATGGCATTCCCCCGAATGAATAATATGAGCTTCTGACTGCTTCCTCCCTCTTTCCTACTGCTTCTGGCTTCTTCCGGAGTTGAAGCTGGTGCCGGAACCGGTTGAACAGTCTATCCTCCCCTAGCCGGTAACCTGGCCCACGCTGGGGCATCCGTTGACCTGACTATCTTCTCCCTTCACTTAGCAGGTGTATCATCAATTCTTGGAGCAATTAACTTCATTACAACCATCATTAATATGAAACCTGCAGCTATTTCCCAATACCAAACACCCCTGTTTGTATGAGCGGTTCTAATTACAGCCGTTCTTCTCCTTCTATCTCTACCCGTTCTTGCTGCGGGGATTACAATACTACTTACAGACCGAAACCTAAACACAACCTTCTTTGACCCTGCGGGAGGAGGGGACCCCATCCTTTATCAGCACCTG
>CRABS_3:Pseudalutarius_cf._nasicornis
CCTTTACATAATTTTCGGCGCCTGAGCCGGAATAGTAGGCACCGCTTTAAGCTTGCTAATCCGGGCAGAACTAAGCCAGCCCGGCGCCCTCCTGGGGGATGACCAAATCTATAATGTAATCGTCACAGCTCATGCCTTTGTAATAATCTTCTTTATAGTGATGCCAATCATGATTGGGGGTTTCGGAAACTGGCTCATCCCCCTAATGATCGGGGCCCCCGACATGGCTTTCCCCCGAATAAATAACATAAGCTTCTGACTCCTCCCCCCCTCCTTCCTTCTTCTCCTTGCCTCTTCCGGGGTGGAAGCAGGGGCCGGCACCGGGTGGACTGTCTACCCTCCCCTTGCAAGTAACCTCTGCCACGCCGGAGCCTCCGTAGACCTCACAATCTTTTCCCTCCATCTTGCAGGAATCTCTTCTATCCTGGGCGCAATCAACTTCATCACAACTATTATTAACATAAAGCCCCCTGCAATCTCTCAATACCAAGTCCCCCTATTCGTCTGAGCTGTCCTCATTACGGCAGTCCTTCTTCTTCTATCGCTTCCTGTGTTAGCGGCAGGCATCACCATGCTCTTGACCGACCGAAATTTAAATACTACATTCTTTGACCCGGCAGGAGGGGGGGACCCTATCTTATACCAACATCTC
```

**Comment by rturba** [comment]
Ooooooooh... I see. You think I might have used the wrong output file!? I'll check that and get back to you ASAP.

**Comment by rturba** [comment]
Ok, yes! The problem was that I was using the original file instead of my actual output from the download. I did another test run and it seems that the taxonomy is working fine. Sorry! And thank you for helping out with this.
