### ISSUE TITLE
OverflowError: FASTA/FASTQ record does not fit into buffer

### ISSUE THREAD

**Issue by mariaelf97** [gjeunen/reference_database_creator#55]
Hello,

I am trying to extract amplicons given a full genome with size about 4.4 MBPs but I got an error telling me this:
OverflowError: FASTA/FASTQ record does not fit into buffer

How would I create amplicons based on my custom primers using CRABS?
`
crabs insilico_pcr --input ../321769-L1.fna --output output.fasta --fwd CCGATCCCGTGCGCAGAAA --rev GCGTCGGTAGGCAAACTGC --error 4.5
`

**Comment by gjeunen** [comment]
Hello @mariaelf97,

This error message is originating from cutadapt, which CRABS uses during the in silico PCR. Basically, the current version of cutadapt has a length restriction, which genomes surpass. To determine if cutadapt can incorporate longer sequences, I suggest you contact the developer. In the meantime, if you are set on using full genomes as input, might I suggest to trim the annotated genomes outside of CRABS to only include the target gene of the primer set. You can then use `db_import` to continue with the CRABS pipeline.

Best,
Gert-Jan
