### ISSUE TITLE
OverflowError

### ISSUE THREAD

**Issue by LuciaRanieri97** [gjeunen/reference_database_creator#57]
Hi everyone,
today, after a pcr in silico command I have got this error. Can you help me?

ERROR: Traceback (most recent call last):
  File "/home/utente/anaconda2/envs/CRABS/lib/python3.6/site-packages/cutadapt/pipeline.py", line 574, in run
    for chunk_index, chunk in enumerate(dnaio.read_chunks(f, self.buffer_size)):
  File "/home/utente/anaconda2/envs/CRABS/lib/python3.6/site-packages/dnaio/chunks.py", line 80, in read_chunks
    raise 
OverflowError: FASTA/FASTQ record does not fit into buffer

Thanks in advance!!! :)

**Comment by gjeunen** [comment]
Hello @LuciaRanieri97,

The error points to a sequence being too long for cutadapt to handle, which CRABS uses during the _in silico_ PCR analysis. This probably occurred by downloading full genome sequences. The recommendation is to avoid longer fragments than mitochondrial and chloroplast genomes. Would this be a suitable option for your use-case or are the genomes essential to be incorporated in the database?

Best regards,
Gert-Jan

**Comment by LuciaRanieri97** [comment]
Thank you very much for the timely response.
I can proceed by streamlining the initial database!

Best regards,
Lucia
