### ISSUE TITLE
Unable to pull crabs image from docker

### ISSUE THREAD

**Issue by eneave** [gjeunen/reference_database_creator#59]
Hi, I've installed docker desktop and had it open while running the "docker pull quay.io/swordfish/crabs:0.1.4" line of code in my terminal and I got these errors and also indication that I needed to install docker/it didn't seem to recognize the command docker: "E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?". 

I've never used docker desktop before but I'm unsure what I am missing here. I thought it just needed to be installed locally. Thank you in advance for your help.

Thank you,
Erika

**Comment by gjeunen** [comment]
Hello @eneave,

Thank you for your question. @hughcross, could you please have a look at this Docker installation issue?

Best wishes,
Gert-Jan

**Comment by hughcross** [comment]
Hi @eneave, This sounds like a Docker issue and not having anything to do with crabs. Pulling an image with the `docker pull` command is the most basic, so should be working for any image. What operating system are you using? When I search with those errors I mostly get answers for Ubuntu, so it seems you have Linux, but let us know and we can try to help. I did find this answer for Linux:

[https://www.geeksforgeeks.org/how-to-fix-unable-to-acquire-the-dpkg-frontend-lock-error-in-ubuntu/](https://www.geeksforgeeks.org/how-to-fix-unable-to-acquire-the-dpkg-frontend-lock-error-in-ubuntu/)

If this is a university or job computer you may need to talk to your IT to get root permissions. 

Keep us posted
