### ISSUE TITLE
Installation warning and db_download does not download sequences

### ISSUE THREAD

**Issue by sarah-nichols** [gjeunen/reference_database_creator#60]
Hi there, I have tried to install CRABS using the manual installation option. To do this, I needed to use a conda environment to load the prerequistite python modules. While I seem to be able to use the software, I get the following warning every time I run a command: 

```
BiopythonDeprecationWarning: The Bio.Application modules and modules relying on it have been deprecated.

Due to the on going maintenance burden of keeping command line application
wrappers up to date, we have decided to deprecate and eventually remove these
modules.

We instead now recommend building your command line and invoking it directly
with the subprocess module.
  warnings.warn(
```

I am afraid I am not familiar with the subprocess module - please can you provide some guidance on how to install the software this way? 

Also, when I attempt to use the download_db module, while the command seems to find a number of sequences to download that are in the correct format, it ultimately reports downloading 0 sequences and an empty fasta file is generated. See below for the command used and the output, I have ommitted some of the identifying information: 

`./crabs db_download --source ncbi --database nucleotide --query '((haemosporidian[All Fields] NOT cytB[All Fields]) NOT cytochrome[All Fields]) NOT cox[All Fields] NOT ("Chordata"[Organism] OR Chordata[All Fields]) NOT "Nycteribia schmidlii"[porgn]' --output /pathtomydata/haemosporidians_nucleotide.fasta --keep_original yes --email [myemail] --batchsize 5000`

And here is the output:

`downloading sequences from NCBI
"--species" parameter not provided, downloading NCBI data based solely on "--query": ((haemosporidian[All Fields] NOT cytB[All Fields]) NOT cytochrome[All Fields]) NOT cox[All Fields] NOT ("Chordata"[Organism] OR Chordata[All Fields]) NOT "Nycteribia schmidlii"[porgn]
looking up the number of sequences that match the query
found 735 number of sequences matching the query
starting the download
temp_/pathtomydata/haemosporidians_nucleotide.fasta_1.fasta: No such file or directory
formatting the downloaded sequencing file to CRABS format
0it [00:00, ?it/s]
found 0 sequences with incorrect accession format
written 0 sequences to /pathtomydata/haemosporidians_nucleotide.fasta`

Thanks for your help with this.

**Comment by gjeunen** [comment]
Hello @sarah-nichols,

Apologies for the slow response, I'm currently out of office!

For your first issue with the deprecation warning, it means that how CRABS implements BioPython won't be updated. This, in theory, however, shouldn't be an issue, as the utilisation of BioPython is fairly simple and we will move away from this software in the new version of CRABS, which we hope will come out in the coming months. The subprocess module would be a different way to invoke BioPython.

Can you please let me know what version of BioPython you are running, as well as your system information. This will allow us to investigate the warning message further.

The code you used for your second query seems to be correct. When I run this I get the following output:

```
downloading sequences from NCBI
"--species" parameter not provided, downloading NCBI data based solely on "--query": ((haemosporidian[All Fields] NOT cytB[All Fields]) NOT cytochrome[All Fields]) NOT cox[All Fields] NOT ("Chordata"[Organism] OR Chordata[All Fields]) NOT "Nycteribia schmidlii"[porgn]
looking up the number of sequences that match the query
found 735 number of sequences matching the query
starting the download
temp_haemosporidians_nucleotide.fasta_1.fasta        [                   <=>                                                                                     ]   1.12M   157KB/s    in 7.3s    
formatting the downloaded sequencing file to CRABS format
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊           | 1082598/1174668 [00:00<00:00, 99357675.36it/s]
found 0 sequences with incorrect accession format
written 735 sequences to haemosporidians_nucleotide.fasta
```

So, it is downloading all sequences without an issue. Can you please upload a screenshot of the Terminal window, so that I can see how your output looks like? Also, do you know if there are any issues with internet connectivity or firewall settings that prevent you from downloading data from NCBI?

Best wishes,
Gert-Jan

**Comment by sarah-nichols** [comment]
Hi @gjeunen, thanks for your reply - sorry for my slow reply, I was also away. The version of Biopython is 1.83 and I am working with a Linux operating system. I do download sequences from NCBI quite often (with both the NCBI Datasets tool and the SRA Toolkit). Here is a screenshot of the output I get when I run the command: 

<img width="1069" alt="Screenshot 2024-07-02 at 19 58 07" src="https://github.com/gjeunen/reference_database_creator/assets/32482022/8220275e-b3b4-4306-80e1-518689ba722e">

**Comment by gjeunen** [comment]
Hello @sarah-nichols,

I realise the specified version of Biopython is 1.78, but could you please try to update it to version 1.84 to see if this resolves the issue for the warning that is printed?

For the downloading, I see that your temp file has a directory path in it. Could you try running CRABS within the folder that you want to place the file? How I have currently implemented this step might not be ideal and might cause issues if you're working out of different paths. If running CRABS in the current directory works, please let me know and I'll fix this issue.

Best wishes,
Gert-Jan

**Comment by sarah-nichols** [comment]
Hi @gjeunen,

Thanks for getting back so quickly! That has fixed the problem and I am now able to run the whole pipeline. Thanks again for your help! 

Best wishes, 

Sarah
