### ISSUE TITLE
primer_efficiency not recovering sequences on file and output structure

### ISSUE THREAD

**Issue by rturba** [gjeunen/reference_database_creator#62]
Hello @gjeunen !

I am trying to use the `primer_efficiency` function but I'm running into an issue. I am using version 0.1.8 in a Linux cluster using gitBash on my PC.

I have downloaded a mitogenome database using NSDPY and imported it to CRABS. I followed with the `in_silico` and downstream steps, including the `pga` function with no problems. For the 12S-V5 primer I've used, I got 562 sequences of Rodentia. However, when I run the `primer_efficiency` funtion, I'm only able to recover 2 sequences. The command is as follows:

```
wd=/home/rachel.turba/promata
indir=$wd/crabs/results/mtgenome
outdir=$wd/crabs/results/mtgenome/visual
raw=$wd/crabs/mtgenomeDB/CRABS_mtgenomes_chordata.fasta

crabs visualization --method primer_efficiency \
	--input $indir/12S/12S-V5_tax_derep_clean.tsv \
	--fwd TAGAACAGGCTCCTCTAG \
	--rev TTAGATACCCCACTATGC \
	--fwd_name 12S-V5-F --rev_name 12S-V5-R \
	--raw_file $raw \
	--tax_group Rodentia \
	--output $outdir/12S/12S-V5_primerEff_rodentia.tsv
```

When I do this for another primer, CO1-mljgXT (with 846 sequences of rodents), I get 843 sequences back:

```
crabs visualization --method primer_efficiency \
	--input $indir/CO1/CO1-mljgXT_tax_derep_clean.tsv \
	--fwd GGWACWRGWTGRACWITITAYCCYCC \
	--rev TAIACYTCIGGRTGICCRAAR \
	--fwd_name CO1-mljgXT-F --rev_name CO1-mljgXT-R \
	--raw_file $raw \
	--tax_group Rodentia \
	--output $outdir/CO1/CO1-mljgXT_primerEff_rodentia.tsv
```

It cannot be something wrong with my command then. And I don't think the primer is the issue, because it was able to recover the sequences for my `in_silico` steps. Has anyone seen this issue before?

Also, in the output for the command, is it safe to assume that the last 3 columns are the fragment that the primer recovers, and the ends where they attach to (forward and reverse)?

**Comment by gjeunen** [comment]
Hello @rturba,

For the `primer_efficiency` method, the primer sequences need to be available for CRABS to include them into the analysis. Would it be possible that the sequences that are left out in this analysis were all included during the `pga` step? As this might mean that the primer sequences are not fully present in the raw reference sequence.

The code does look fine indeed.

Thanks,
Gert-Jan

**Comment by rturba** [comment]
I thought that could be the case, but:

1. I actually don't have an increase in sequence number when I do the `pga` step. I keep the same from the previous `in_silico` one.
3. And also, I'm working with a mitogenome database, so technically the primer region should be there.

I'm really confused by this :/

**Comment by gjeunen** [comment]
Thanks for the additional info. It does seem that there might be a bug in the code. I'll try and fix it, but this may take some time, as I'm currently out of office. I hope to get something to you by the end of August. Apologies for the delay.

Best wishes,
Gert-Jan

**Comment by gjeunen** [comment]
Hello @rturba,

My sincere apologies that it took me this long to respond!

`crabs --version 1.0.0` is now available and can be downloaded by cloning the GitHub repo (we hope to update the Docker container and conda package shortly). This version should resolve your issue, but please reopen this thread if the issue persists.

Best wishes,
Gert-Jan
