### ISSUE TITLE
empty temp files when downloading NCBI

### ISSUE THREAD

**Issue by mikeallen-eco** [gjeunen/reference_database_creator#63]
Hello,
Many of the temporary files generated by the following NCBI download code (using Linux) have 0 bytes, and it happens differently each time I repeat it. The result is that the final fasta file varies in size (44 to 300+ MB). It also happens for other large insect orders (e.g., Diptera). I'm guessing this may be from NCBI/entrez connection errors(?), but no indication of an error is provided. So, it is hard to know which downloads to trust. I'm using CRABS v. 0.1.8 installed via cloning from GitHub. Thanks, 
Mike

```
crabs db_download \
--source ncbi \
--database nucleotide \
--query "((Coleoptera[Organism] OR Coleoptera[All Fields]) AND mitochondrion[filter])" \
--keep_original no \
--email my_email@email.edu \
--batchsize 5000 \
--output "ncbi_Coleoptera.fasta"
```

**Comment by gjeunen** [comment]
Hello @mikeallen-eco,

Thank you for using CRABS. 

The file sizes can differ based on sequence length. However, the fact you're observing 0 byte intermediate files does indeed point to an unstable network connection, an overload of the NCBI servers, or restricted access on your account based on too much usage. 

To get an idea of which download to trust, I will need to write a script that checks the number of sequences after each download to verify the number of sequences matches the batch size. In case the numbers don't match, the script could redownload these sequences. In case multiple times the download was unsuccessful, I could make CRABS error out or continue based on the last download via user input. Would this be what you're after?

Thanks,
Gert-Jan

**Comment by mikeallen-eco** [comment]
Yes, I think that would be a great feature to add. The thought of possible hidden problems with the downloads was troubling me. Thanks for the response (and the software)!

Mike

**Comment by gjeunen** [comment]
Perfect, I will add it to the list of items to add in the next version of CRABS.

Thanks,
Gert-Jan

**Comment by gjeunen** [comment]
Hello @mikeallen-eco,

`crabs --version 1.0.0` is now available and can be downloaded by cloning the GitHub repo (we hope to update the Docker container and conda package shortly). This version should resolve your issue, but please reopen this thread if the issue persists.

Best wishes,
Gert-Jan
