### ISSUE TITLE
in silico PCR error

### ISSUE THREAD

**Issue by saraswaminathan** [gjeunen/reference_database_creator#69]
Hi there, when I try to run the in silico PCR on a merged file containing sequences from BOLD, I get the following error

```
|            Function | Extract amplicons through in silico PCR
|         Import data | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:01
|  Transform to fasta | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:00
|       In silico PCR | ╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   1% 0:00:02 0:00:00
Traceback (most recent call last):
  File "/Users/saraswaminathan/reference_database_creator/crabs", line 844, in <module>
    crabs()
  File "/Users/saraswaminathan/miniconda3/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saraswaminathan/miniconda3/lib/python3.12/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/saraswaminathan/miniconda3/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saraswaminathan/miniconda3/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saraswaminathan/reference_database_creator/crabs", line 611, in crabs
    trimmed_seqs, untrimmed_seqs = cutadapt(console, columns, adapter, temp_input_path, fasta_dict, mismatch_, overlap, threads_)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saraswaminathan/reference_database_creator/function/crabs_functions.py", line 1094, in cutadapt
    if seq != fasta_dict[header]:
              ~~~~~~~~~~^^^^^^^^
KeyError: '>crabs_11695_Mogoplistidae\tMogoplistidae\t1301073\tEukaryota\tArthropoda\tInsecta\tOrthoptera\tMogoplistidae\tNA\tNA\tCCTCTATFatal error: Uncaught <table style="border: 1px" cellspacing="0"><tr><td colspan="3" style="background: #ff9999"> <b>HTTP_Request2_MessageException</b>: Request timed out due to default_socket_timeout php.ini setting in <b>/usr/share/pear/HTTP/Request2/SocketWrapper.php</b>
```

The last section of that says "KeyError" goes on for a really long time and is unintelligible so I cut it off after a few lines just so you could see. I tried the in-silico-PCR command with the primer sequences in your example and some other ones as well, and I got the same error both times.

I am running python 3.12.4 with cutadapt 4.9 on an M2 macbook pro running Ventura 13.2.1

**Comment by gjeunen** [comment]
Hello @saraswaminathan,

Could you please provide the exact code you have been using thus far? I've tried to recreate the error by running the following lines, but didn't receive any errors. FYI, the primers I used are the standard COI primers for metabarcoding. The KeyError you are receiving indicates that there is something wrong with the sequence headers, so maybe the file is wrongly parsed. Any additional info would be greatly appreciated.

```{code-block} bash
crabs --download-bold --taxon Mogoplistidae --output bold_mogoplistidae.fasta
crabs --download-taxonomy
crabs --import --import-format bold --names names.dmp --nodes nodes.dmp --acc2tax nucl_gb.accession2taxid --input bold_mogoplistidae.fasta --output crabs_bold.txt --ranks 'superkingdom;phylum;class;order;family;genus;species'
crabs --in-silico-pcr --input crabs_bold.txt --output crabs_bold_insilico.txt --forward GGWACWGGWTGAACWGTWTAYCCYCC --reverse TAIACYTCIGGRTGICCRAARAAYCA
```

Best wishes,
Gert-Jan

**Comment by saraswaminathan** [comment]
Hi Gert-Jan, 
My original workflow involved downloading hundreds of small fasta files, importing and merging all of them, and then conducting the in-silico PCR. I am now downloading fewer, larger fasta files, and have had no issue with the in-silico PCR since making that change.

**Comment by mrmrwinter** [comment]
Hello to anyone arriving here after experiencing a similar error.

I also experienced this error when trying to run crabs. 

I found that the error is coming from, I think, the --import stage. An error is occurring, and the error text that should go to STDOUT/STDERR is instead getting written into the --import output file, then when --insilico step tries to read it it throws this error and prints the fasta header containing the text from the previous error. 

Repeating the import step for the offending taxa and remerging before --insilico fixed the issue.

**Comment by mrmrwinter** [comment]
Since my last post, I tried to add some more taxa and then merge and perform insilico, but it failed with the same error, coming from a taxa that had previously been imported, merged, and insilico'd without error. 

This suggests that the error is not in fact coming from issues in the import stage, as the offending taxon was already imported.
