### ISSUE TITLE
Trying to create reference database from downloaded fasta file

### ISSUE THREAD

**Issue by dylanstephen-s** [gjeunen/reference_database_creator#78]
I would like to create a reference database by a fasta file that I have manually curated for a specific taxonomic group. Is there a way to do this with bypassing the download step?

**Comment by gjeunen** [comment]
Hello @dylanstephen-s,

Yes, you can start from the `--import` function in CRABS to run through the workflow with manually downloaded reference sequences. The format of your file would need to fit the supported formats, however, which are the formats used by the online repositories from which CRABS downloads sequences. To check if your sequences follow a supported format, I suggest to download a couple of sequences from each online repository.

Best wishes,
Gert-Jan
