### ISSUE TITLE
Error when assigning taxonomy

### ISSUE THREAD

**Issue by mrgambero** [gjeunen/reference_database_creator#8]
Hello,

I am trying to build my own database but at the step when downloading taxonomy, 
when running this code: crabs db_download --source taxonomy

I get the following error:

downloading taxonomy information
dyld: lazy symbol binding failed: Symbol not found: _libiconv_open
  Referenced from: /Users/gabri/opt/miniconda3/envs/CRABS/bin/wget
  Expected in: /usr/lib/libiconv.2.dylib

dyld: Symbol not found: _libiconv_open
  Referenced from: /Users/gabri/opt/miniconda3/envs/CRABS/bin/wget
  Expected in: /usr/lib/libiconv.2.dylib

unzipping nucl_gb.accession2taxid.gz...
gunzip: can't stat: nucl_gb.accession2taxid.gz (nucl_gb.accession2taxid.gz.gz): No such file or directory
dyld: lazy symbol binding failed: Symbol not found: _libiconv_open
  Referenced from: /Users/gabri/opt/miniconda3/envs/CRABS/bin/wget
  Expected in: /usr/lib/libiconv.2.dylib

dyld: Symbol not found: _libiconv_open
  Referenced from: /Users/gabri/opt/miniconda3/envs/CRABS/bin/wget
  Expected in: /usr/lib/libiconv.2.dylib

removing intermediary files

Traceback (most recent call last):
  File "/Users/gabri/opt/miniconda3/envs/CRABS/bin/crabs", line 1372, in <module>
    main()
  File "/Users/gabri/opt/miniconda3/envs/CRABS/bin/crabs", line 1369, in main
    args.func(args)
  File "/Users/gabri/opt/miniconda3/envs/CRABS/bin/crabs", line 66, in db_download
    os.remove(file)

Any idea on how to solve this?
Thanks in advance,
Gabri

**Comment by gjeunen** [comment]
Hello Gabri,

At first glance, this is either an issue with "git" or "wget". Are other commands within CRABS working for you? For example, downloading the MitoFish database (the quickest to download). Or is the issue only appearing for this specific command?

If it is only this specific command that is failing, could you please run the following command in your Terminal (not using CRABS):
```
wget ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/nucl_gb.accession2taxid.gz -q --show-progress
```
This command should download a single file "nucl_gb.accession2taxid.gz" to your path. Can you let me know if this works?

If other commands are failing within CRABS as well, could you check the git version and if you might have two different versions installed on your system at 2 different paths?

Regards,
Gert-Jan

**Comment by mrgambero** [comment]
Hello  Gert-Jan,

Thanks for the fast answer and for your work!
I solved by downloading the nucl_gb.accession2taxid.gz and the other taxa file by ftp and used them further.

Gabri

**Comment by gjeunen** [comment]
Hello Gabri,

Can I assume that the other commands of CRABS are working for you? If so, I'll close this issue.

Regards,
Gert-Jan

**Comment by mrgambero** [comment]
Yes, everything else working!

Thanks a lot!

Gabri

**Comment by hughcross** [comment]
Hello Gabri or anyone else coming across this issue,

I did some checking, and updating the version of wget seemed to fix the problem and the Crabs command now works. In your crabs environment, run this command:

```
conda install wget=1.21.3
```
That should fix for now. We will try to get the updated wget into the conda package as soon as we can.

cheers,

hugh
