### ISSUE TITLE
Specify download location; manual installation; db_download NCBI batch size; db_import with BOLD

### ISSUE THREAD

**Issue by marymcelroy** [gjeunen/reference_database_creator#9]
Hi @gjeunen, I'm getting started with crabs (db_download), and I wonder if there is an easy way to point the file downloads to a specific location? I'm working on my personal laptop (Mac), but I have an external SSD where I'd like the files to go. I'm worried about not having enough space on my computer for the downloads. In the same general vein - are there any particular computational/storage hazards I should be aware of while running crabs? Are all modules manageable with a personal laptop? For context, I'm looking to set up COI, 16S, and 18S reference databases for eukaryotes. Any suggestions would be much appreciated - thanks for such a great tool!

**Comment by hughcross** [comment]
Hi Mary,

Thanks for your interest in Crabs! There are a couple of things you could do. I think for downloading the NCBI etc. databases, you should be able to add a path to the --output parameter (e.g. `--output /Volumes/ssd/path/ncbi.fasta`). However, for downloading the taxonomy files (`crabs db_download --source taxonomy`) I am not sure if this is possible. Gert-Jan should be able to answer that. Another way to do this is to move into the external hard drive on your terminal. On macs, these are found in the `/Volumes` folder. So you could run `ls /Volumes' and you should see your hard drive.

One tip to quickly find file paths on Macs is to find the folder you want in the Finder window. You can then drag that folder to a terminal and the path to the folder should appear in the terminal prompt. You can select and copy that and paste it in to your command. 

I am in the process of moving to a new Mac, so need to install Crabs on their, but I will do that soon and can test it if you are still having issues. Some of the database files can be quite large so this is an important question. Thanks

Cheers,
Hugh

**Comment by marymcelroy** [comment]
Thanks, Hugh! Unfortunately it didn't work when added a path to the --output parameter, but it did work by just switching my working directory to the external drive folder where I wanted the files. I only tried with a small test dataset for ncbi download, but I'll keep going and see what happens doing it this way!

**Comment by hughcross** [comment]
Good to know. Thanks. We will look into expanding some of these functions to future versions. 

When you are running your pipeline to use the Crabs database you are building, you should be able to just input the path to the reference on the SSD. I have done some testing with Crabs on a server where the reference files were on another drive, but let me know if you run into issues. Getting to know how to use paths and linking all your data together can be one of the trickiest things when starting out. 

I will leave this issue open for now, as Gert-Jan may like to weigh in. Keep us posted
cheers

**Comment by marymcelroy** [comment]
Hi again, just coming back with a few db download issues that I haven't been able to resolve. Let me know if you can help! I did successfully grab seq data from BOLD and NCBI for 16S and 18S eukaryotes, but I'm having the following issues with NCBI/COI, MitoFish, EMBL, and taxonomy:

1. I don't have the terminal output to copy/paste but my NCBI download query for eukaryote COI (below) found >4mil sequences, but only wrote ~800,000 to the output files. No error returned and the batch count looked right (over 40 fasta output files), but I'm wondering about this mismatch in seq # when the smaller NCBI queries (16s and 18s) wrote all sequences found. `crabs db_download --source ncbi --database nucleotide --query '("CO1"[GENE] OR "COI"[GENE] OR "COX1"[GENE] OR "COXI"[GENE]) AND Eukaryota[Organism] AND mitochondrion[filter]' --output COI_ncbi.fasta --keep_original yes --email mcelroy@ucsb.edu --batchsize 100000`

2. Mitofish query returned this:
`crabs db_download --source mitofish --output mitofish.fasta --keep_original`

```
downloading sequences from the MitoFish database
dyld[17353]: missing symbol called
Traceback (most recent call last):
  File "/opt/anaconda3/envs/crabs/bin/crabs", line 1372, in <module>
    main()
  File "/opt/anaconda3/envs/crabs/bin/crabs", line 1369, in main
    args.func(args)
  File "/opt/anaconda3/envs/crabs/bin/crabs", line 96, in db_download
    dl_file = mitofish_download(url)
  File "/opt/anaconda3/envs/CRABS/lib/python3.6/site-packages/function/module_db_download.py", line 139, in mitofish_download
    os.remove('complete_partial_mitogenomes.zip')
FileNotFoundError: [Errno 2] No such file or directory: 'complete_partial_mitogenomes.zip'
```

3. Several EMBL queries returned this:
`crabs db_download --source embl --database 'inv*' --output embl_inv.fasta --keep_original yes`

```
downloading sequences from EMBL
dyld[17340]: missing symbol called
Combining all EMBL downloaded fasta files...
formatting intermediary file to CRABS format
0it [00:00, ?it/s]
found 0 sequences with incorrect accession format
written 0 sequences to embl_inv.fasta
```

4. taxonomy grab returned this:
`crabs db_download --source taxonomy`

```
downloading taxonomy information
dyld[17346]: missing symbol called
unzipping nucl_gb.accession2taxid.gz...
gunzip: can't stat: nucl_gb.accession2taxid.gz (nucl_gb.accession2taxid.gz.gz): No such file or directory
dyld[17348]: missing symbol called
removing intermediary files

Traceback (most recent call last):
  File "/opt/anaconda3/envs/crabs/bin/crabs", line 1372, in <module>
    main()
  File "/opt/anaconda3/envs/crabs/bin/crabs", line 1369, in main
    args.func(args)
  File "/opt/anaconda3/envs/crabs/bin/crabs", line 66, in db_download
    os.remove(file)
FileNotFoundError: [Errno 2] No such file or directory: 'citations.dmp'
```

**Comment by hughcross** [comment]
Hi Mary,

These issues all share in common some missing libraries (dyld). I am not sure, but this may be a problem with newer macs with newer M1 processors. Can you tell me what kind of mac and processor you have?

**Comment by marymcelroy** [comment]
Hi Hugh, thanks for getting back to me. I'm working on a 2017 Macbook Pro with a 2.3 GHz Dual-Core Intel Core i5 processor and OS Monterey 12.3.1.

**Comment by hughcross** [comment]
Hi Mary, Your computer should not be a problem. I am using the same OS and have not seen that issue. I am sorry, I am not sure what is wrong. It may be related to the conda environment or a larger system issue with your mac. you could try installing the conda env again, or doing the custom install option. We are working on improving both of those options. I will keep looking into it and see if I can find a solution. 

cheers,

hugh

**Comment by marymcelroy** [comment]
Thanks, Hugh. I'll play around and see if I can figure it out. Any ideas about the potential issue with the NCBI COI query (#1 above)? The NCBI db_download seemed to work just fine for all 16S and 18S eukaryote seqs found (albeit with much fewer seqs), but the crabs output indicated only ~800,000 out of >4mil 'found' COI seqs were successfully downloaded.

I guess I could try moving forward with only NCBI+BOLD downloads, but I would still have I problem if I can't get the taxonomy download to work.

**Comment by hughcross** [comment]
Hi Mary,

I had a little more time today to dig a little deeper into your issues. First off for the NCBI download, I ran the same command and it seems to be working (still going, as it is a lot of sequences). One thing I noticed is that checking the temp files, there are only 10,000 sequences in each, not 100,000. I am not sure why, but it might be good to lower the batchsize. You can probably find guidelines on the NCBI website. Though, you have to check the number of sequences in each temp file and not just the number of files.

One thing that may be happening is that the request is just timing out. NCBI puts limits on how much data any one user can download, and depending on the internet connection, large demands may be curtailed, often without any notice or warning. Try running it overnight when there is less traffic. 

I would suggest curtailing your search parameters. Four million sequences is a lot to download at once. Do you really need all Eukaryotes? Your EMBL search was for only invertebrates. Just changing the Eukaryota[Organism] to Insecta[Organism] brought it down to 2.7 million. Still a lot, but might help. Lowering the batch size and constricting the parameters may work. Try running it again and see if it helps.

As for the other download commands, they all share use of the wget tool, which is installed with Crabs. We have had  issues between Linux and Mac versions of wget, but we have not seen any issues yet within Mac. In the crabs environment, try running `wget -h` and check the version number at the top of the output. It should be 1.20.3. You could try to reinstall this within the Crabs environment: `conda install wget --force-reinstall`. This will install a new version of wget and perhaps also any missing libraries. It may not help, but is worth a shot and should not affect anything else. 

That is all I can think of for now. Let me know how it goes and I will keep the thinking cap on.

cheers,

**Comment by marymcelroy** [comment]
Following up with progress on these issues:

Reducing the ncbi query batch size to 10000 helped recover more COI sequences - looks like I was able to get 3.8 out of 4.1M while running it overnight. Still not sure why I can't get 100% seq recovery, but maybe a time-out issue like you 

My wget version was correct, but unfortunately a force reinstall in crabs still did not resolve the previous missing symbol errors during db_download. Tried **manual installation** of crabs according to the github instructions - that did work! I was able to complete the remaining db_downloads.

I tried moving on to the insilicopcr step 4 with the mitofish sequence subset and got stuck again. Looks like a problem with locating cutadapt, even though I have it installed already:
`crabs insilico_pcr --input mitofish.fasta --output mitofish1.fasta --fwd GGWACWRGWTGRACWITITAYCCYCC --rev TAIACYTCIGGRTGICCRAARAAYCA --error 4.5`
```
reading mitofish.fasta into memory
100%|██████████████████████| 686140221/686140221 [00:01<00:00, 386896578.11it/s]
found 751440 sequences in mitofish.fasta
running in silico PCR on fasta file containing 751440 sequences
Traceback (most recent call last):
  File "/Users/marymcelroy/reference_database_creator/crabs", line 1372, in <module>
    main()
  File "/Users/marymcelroy/reference_database_creator/crabs", line 1369, in main
    args.func(args)
  File "/Users/marymcelroy/reference_database_creator/crabs", line 230, in insilico_pcr
    sp.call(cmnd_cutadapt_1)
  File "/opt/anaconda3/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/anaconda3/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.8/subprocess.py", line 1706, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cutadapt'
```
Some troubleshooting looking into cutadapt:
`python3 -m pip install --user --upgrade cutadapt`
```
Requirement already satisfied: cutadapt in ./.local/lib/python3.8/site-packages (4.1)
Requirement already satisfied: xopen>=1.1 in ./.local/lib/python3.8/site-packages (from cutadapt) (1.6.0)
Requirement already satisfied: dnaio>=0.7.1 in ./.local/lib/python3.8/site-packages (from cutadapt) (0.9.1)
Requirement already satisfied: isal>=1.0.0 in ./.local/lib/python3.8/site-packages (from xopen>=1.1->cutadapt) (1.0.1)
```
`cutadapt --version` 
```
zsh: /usr/local/bin/cutadapt: bad interpreter: /usr/bin/python: no such file or directory
```
`cutadapt -h`
```
zsh: /usr/local/bin/cutadapt: bad interpreter: /usr/bin/python: no such file or directory
```

**Comment by hughcross** [comment]
Thanks for the update Mary.

Because we had you follow the pip install of Cutadapt instead of the conda install (to avoid any potential issues with conda), you have to add the path to cutadapt for Crabs (and your system) to find it. I checked this on my system, and it worked. So add this line to your .bash_profile file (or .zshrc if you are using zsh shell). 

```
export PATH="/Users/<username>/.local/bin:$PATH"
```

This is the same process you went through to add the path to Crabs to your system. In the above line, change <username> to your own username. If in doubt, go to your home directory and check where you are (`cd; pwd` should do it). Remember to be careful modifying your .bash_profile or .zshrc files. 

More information can be found on the [**Cutadapt online guide**](https://cutadapt.readthedocs.io/en/stable/installation.html#installation-with-pip). 

For everyone: if further problems occur with the conda install option, we will put more explicit instructions for the manual install, and start recommending that one instead.

**Comment by gjeunen** [comment]
Hello Mary,

With regards to batch size downloading and the missing sequences, this is due to NCBI timing out. NCBI prefer a limit of 5000 sequences to be downloaded each time, the reason we set this value as the default. Could you please try the db_download function with a --batchsize value of 5000 or less?

Please let me know if you encounter any issues.

Best regards,
Gert-Jan

**Comment by marymcelroy** [comment]
Thanks, Hugh and GJ! I added the cutadapt path to my .zshrc file and that resolved the error. I'll also re-try the NCBI downloads with batchsize=5000. Testing with the mitofish sequence data for steps 1, 4-8.2 all seem be working great now.

Thanks for your patience and guidance so far!

**Comment by marymcelroy** [comment]
Hi again - I've got most features working now, so that's great! I wanted to ask about a couple of new things:

1. I was experiencing timeout problems with crabs+bold download, so I used a workaround for acquiring bold seq records that aren't mined from GenBank by manually downloading fasta files from their website with more complex queries than crabs could accommodate. I then used db_import without any issues:
`crabs db_import --input bold.fasta --output bold_crabs.fasta --seq_header accession --delim '|'`
However, the subsequent insilico pcr and assign_tax features are not working, possibly because bold uses process ids and not accession numbers? It seems like maybe there's a formatting issue. I also tried the above code with 'species' instead of 'accession' and same problem. After db_import, the fasta record headings are formatted like >CRABS:CQCS058-10

`crabs insilico_pcr --input bold_crabs.fasta --output bold_pcr.fasta --fwd GGWACWRGWTGRACWITITAYCCYCC --rev TAIACYTCIGGRTGICCRAARAAYCA --error 2`
```
Fatal error: Illegal character '-' in sequence on line 6 of FASTA file
running in silico PCR on 50368 reverse complemented untrimmed sequences
counting the number of sequences found by in silico PCR
0it [00:00, ?it/s]
found primers in 0 sequences
```
`crabs assign_tax --input bold_crabs.fasta --output bold_tax.tsv --acc2tax nucl_gb.accession2taxid --taxid nodes.dmp --name names.dmp`
```
assigning a tax ID number to 40118 accession numbers from bold_crabs.fasta
did not find a tax ID found for 40118 entries, most likely due to spelling mistakes.
did not find 0 accession numbers in nucl_gb.accession2taxid
0 accession numbers resulted in 0 unique tax ID numbers
generating taxonomic lineages for 0 tax ID numbers
assigning a taxonomic lineage to 40118 accession numbers
written 0 entries to bold_tax.tsv
```

2. I tried the db_completeness feature. It looked like the code was running successfully but it never produced a visualization? No errors either. This is the code I used:
`crabs visualization --method db_completeness --input COIsyn_geocurate.tsv --species CAsynonyms.txt --taxid nodes.dmp --name names.dmp`

**Comment by marymcelroy** [comment]
Hi @hughcross and @gjeunen - do either of you have any thoughts about these new issues I'm experiencing (described above)? Thanks!

**Comment by hughcross** [comment]
Hi Mary,

It sounds like the bold fasta file just needs some cleaning up before further processing. For the illegal character, a short script or one-liner can probably clean these up. The '-' character usually means a gap in an alignment file. Is that what you have? These can be taken out. Other illegal characters can be replaced with an 'N'. Try outputting the first 20 lines or so of the file and paste it in the response:

```
head -n 20 bold_crabs.fasta > bold_example.fasta
```

For the second issue, we have to look at the sequence headers and see if they are not NCBI- compatible or annotated in some way that the assign_tax does not recognize. The example as I suggest above might show us what we need.

We should probably start new issues for these new problems and close this one. This will help other people find them. For now, though, let's solve the current dilemmas.

**Comment by hughcross** [comment]
Thanks Mary. It is clear now. The gaps can be fixed with a few lines of code, or a clever sed or awk line. I will add that here soon. 

For the taxonomy assignment, that is more of a problem with the manual BOLD download. The sequences are named with BOLD accession numbers, and as the Crabs assign_tax tool uses NCBI accession numbers to match, that won't work. You can query the BOLD website to get the taxonomy, but I don't know how to do that for a bunch of sequences. They may have a tool for that. I will try to look more into it.

**Comment by gjeunen** [comment]
Hello Mary,

Apologies for the silence, it's been a bit hectic lately. Please find my responses below for the two queries you have posted below. If I have missed something, please let me know. Also, might I please ask that if you have queries for a different topic, as being discussed in this thread, that you place them as separate issues? Currently this thread is named "Specify download location", but none of the topics discussed below are dealing with this issue. Using separate issue threads will make it easier for people to find potential answers if they come across a similar issue.

1) With regards to the BOLD formatting. The issue here is that the CRABS `db_import` function is a very simple line of code that can only handle something in the format of:
```
>species name
ACGT
>acc_number
ACGT
```
The `db_import` function doesn't have the capability for people to download BOLD sequences outside of CRABS and then use CRABS `db_import` to format the data appropriately. Please give me a some time to write the code to add in this functionality into the `db_import` function.

2) With regards to the `db_completeness` function, you will need to specify an output file name with ".txt" extension using the `-o` or `--output` parameter.

**Comment by gjeunen** [comment]
Hello Mary,

You should now be able to import your BOLD sequences into CRABS using the following command:
```
crabs db_import -i filename.fasta -o outfile.fasta -s BOLD
```
This should now give you the correct CRABS format to be used in the remainder of the pipeline. Please remember to update CRABS to the latest version.

**Comment by marymcelroy** [comment]
Hi Gert-Jan, thank you so much for your help. My BOLD seqs are working with the pipeline now.

My apologies for using the same thread - I edited the issue title to be more informative so hopefully it will still be useful for people seeking help on similar issues!

**Comment by hughcross** [comment]
I will close this issue now as this has covered a lot. For anyone having similar issues, please open a new issue
